receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  debug: {}   # <— reemplaza logging por debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
