name: Build container and run VISE API testing

on:
  workflow_dispatch:
    inputs:
      PORT:
        description: 'The port of your application'
        required: true
        default: "3000"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Descargar el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Instalar docker
      - name: Setup docker
        uses: docker/setup-buildx-action@v3

      # Construir imagen de docker
      - name: Build docker image
        run: |
          docker build -t vise-api:latest .

      # Levantar contenedor
        
      - name: Run container
        run: |
          docker run -d -p ${{ github.event.inputs.PORT }}:${{ github.event.inputs.PORT }} --name vise-api vise-api:latest
          
          echo "⏳ Esperando que el API esté disponible..."
          for i in {1..15}; do
            if curl -s http://localhost:${{ github.event.inputs.PORT }}/health > /dev/null; then
              echo "✅ API está lista"
              break
            fi
            echo "Intento $i: API aún no responde..."
            sleep 3
          done


      # Instalar hurl (API testing tool)
      - name: Setup hurl (API testing tool)
        uses: gacts/install-hurl@v1

      # Ejecutar pruebas con hurl
      - name: Test API
        run: |
          hurl \
            --variable host=http://localhost:${{ github.event.inputs.PORT }} \
            --error-format long \
            --test session.hurl
